fix(auth): resolved bug issue
